/* SPDX-License-Identifier: (GPL-2.0+ OR BSD-3-Clause)*/

#ifndef _DT_BINDINGS_RESET_CONTROLLER_MT6789
#define _DT_BINDINGS_RESET_CONTROLLER_MT6789

/* INFRA resets */
#define MT6789_INFRA_RST0_LVTS_AP_SWRST		0
#define MT6789_INFRA_RST1_UFSHCI_SWRST		1
#define MT6789_INFRA_RST2_UNIPRO_SWRST		2
#define MT6789_INFRA_RST3_UFS_CRYPTO_SWRST	3

#endif  /* _DT_BINDINGS_RESET_CONTROLLER_MT6789 */
